[db]
username = "username"
password = "password"
host = "localhost:5432"
name = "database-name"
occurrence_table = "database-occurrence-table-name"
detail_table = "database-session-details-table-name"
