services:
  ebms-db.dev:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=ebms-analytics
      - POSTGRES_USER=ebms
      - POSTGRES_PASSWORD=ebms-pass
    ports:
      - ${PORT:-5432}:5432
    volumes:
      - ./db/seed:/docker-entrypoint-initdb.d
      - ebms-db-dev:/var/lib/postgresql/data

volumes:
  ebms-db-dev:
