CREATE TABLE ocurrence (
    "id"  BIGSERIAL PRIMARY KEY,
    "sample_id" INTEGER NOT NULL,
    "occurrence_id" INTEGER NOT NULL UNIQUE,
    "location" VARCHAR(255) NOT NULL,
    "location_id" INTEGER NOT NULL,
    "country" VARCHAR(50),
    "date" DATE NOT NULL,
    "recorder_name" VARCHAR(255) NOT NULL,
    "identified_by" VARCHAR(255) NOT NULL,
    "accepted_species_name" VARCHAR(255) NOT NULL,
    "authority" VARCHAR(255),
    "family" VARCHAR(255) NOT NULL,
    "verification_status" boolean DEFAULT false,
    "verified_by" VARCHAR(255),
    "count_inside" INTEGER NOT NULL DEFAULT 0,
    "count_outside" INTEGER NOT NULL DEFAULT 0,
    "count" INTEGER GENERATED ALWAYS AS (count_inside + count_outside) STORED,
    "latitude_full" VARCHAR(255) NOT NULL,
    "longitude_full" VARCHAR(255) NOT NULL,
    "latitude" INTEGER,
    "longitude" INTEGER,
    "record_status" VARCHAR(50),
    "record_substatus" VARCHAR(50),
    "comments" TEXT,
    "occurrence_comment" TEXT,
    "created_at" timestamp default current_timestamp,
    "updated_at" timestamp default current_timestamp
);
